### PR TITLE
Created contact history section in contact profile

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

Created contact history section in contact profile

## Test Plan

Added

### CODE REVIEW

**Review by kurund — CHANGES_REQUESTED** [review]
@mdshamoon 

Contact history seems to be caching the data and not showing correct information.

Go to any contact view history, then start a flow and visit contact history again. It does not display new flow information. If you hard refresh correct data is shown.

**Comment by mdshamoon** [comment]
@kurund updated with the given feedbacks.

**Review by kurund — CHANGES_REQUESTED** [review]
@mdshamoon 

Now it's showing the correct data. However, there is a minor glitch with the 'Show more' action.

It is shown even though it's not needed. Hard refresh removes the button.

Screenshot 2021-12-13 at 11 48 18 PM

**Review by kurund — APPROVED** [review]
All the edge cases are now resolved, good to merge.

**Pull request merged**
