### PR TITLE
Interactive message image fixes

### PR DESCRIPTION
**Pull request by kurund**
fixes: https://github.com/glific/glific-frontend/issues/2227

### CODE REVIEW

**Review by mdshamoon — COMMENTED** [review]
@kurund I think the validation is already present from the backend its just that we don't wait for the validation to complete and allow saving the interactive message before that.

I don't think we need to explicitly check for webp format here.

**Comment by kurund** [comment]
@mdshamoon 

I don't think backend validation is working for Interactive messages as we are able to save Stickers as mentioned in the UI.

However, in addition to the backend, it would be good to validate the same on the frontend.

One to chat during our call.

**Comment by mdshamoon** [comment]
@kurund just one more thing on this if we can wait for the backend validation before saving. I can save a video with a image URL as well if I do it quickly.

**Comment by kurund** [comment]
@mdshamoon 

I have updated the PR as per our discussion to disable the save action while validation is in progress.  Can you please check?

**Review by mdshamoon — APPROVED** [review]

**Pull request merged**
