### PR TITLE
Support for adding bulk contacts to group

### PR DESCRIPTION
**Pull request by rathorevaibhav**
## Summary

We can add bulk contacts to a group from the group list screen

### CODE REVIEW

**Review by kurund — CHANGES_REQUESTED** [review]
@rathorevaibhav Mostly everything is working as expected. However, I am getting this weird behavior when I search for contact and then select the contact. The form just breaks after that.
Screenshot 2020-10-20 at 6 56 36 PM

**Comment by rathorevaibhav** [comment]
hey @kurund I tried a few combinations but couldn't replicate it. can you share some more details or maybe the exact steps you're doing?

**Comment by kurund** [comment]
We already discussed, just adding it here for future reference. It happens when you try to search for a contact that is not part of the preloaded contacts.

**Review by kurund — APPROVED** [review]
Looks good and working as expected now.

**Pull request merged**
