### PR TITLE
Subscription reloaded

### PR DESCRIPTION
**Pull request by kurund**
## Summary

* Abstract chat subscriptions and move to separate component
* Move subscriptions to top-level so that it can listen to other events like the message to a group

## Test Plan

* Not needed

### CODE REVIEW

**Comment by rathorevaibhav** [comment]
I can't log in. The login page redirects to the logout page and vice versa in a loop. @kurund can you check if it's happening for you too?

**Comment by kurund** [comment]
@rathorevaibhav working as expected for me.

**Comment by rathorevaibhav** [comment]
hey @kurund I'm still getting the issue with the login and it keeps reloading on loop.

**Comment by kurund** [comment]
@rathorevaibhav Fixed the issue related to logout

**Pull request merged**
