### PR TITLE
Feature/formik-material

### PR DESCRIPTION
**Pull request by rathorevaibhav**
## Summary
Formik and Formik-material implementation as an alternative of Formsy.

## Test Plan

To be done separately in #14

### CODE REVIEW

**Comment by kurund** [comment]
@rathorevaibhav Can you remove yarn.lock from your commit. I see you had added it .gitgnore

**Comment by rathorevaibhav** [comment]
@kurund done with changes. Please check

**Comment by rathorevaibhav** [comment]
Yeah, I had to run `yarn install` for the Formik packages and that updated yarn.lock

That is why it contains changes regarding the new packages

**Comment by kurund** [comment]
@rathorevaibhav I think what you have done is correct. i.e adding it to .gitignore.
so it should not be listed as a part of your commit.

**Pull request merged**
