### PR TITLE
Login Issue #2093 fixed

### PR DESCRIPTION
**Pull request by enigmaticmahesh**
## Summary

Login Issue #2093 Fixed

### CODE REVIEW

**Review by mdshamoon — COMMENTED** [review]
In some cases the refresh token takes time and we need to retry after the authentication fails one time. Not sure if we should not retry if authentication fails once. We should do something on the login screen end that if we reach the login screen then don't open the popup.

Or maybe there should not be a need for retry after the authentication fails.
Let's discuss this tomorrow in our call.

**Review by kurund — COMMENTED** [review]
@enigmaticmahesh 

This issue occurs because we are auto retying to renew session in case of errors.

The current fix should be fine for the reported issue. However, we should do some more testing for the cases where in we auto-renew session using re-try. 

@mdshamoon  Can you also please test scenarios mentioned above and also the flow editor part?

Let's have chat tomorrow if you need anything

**Comment by enigmaticmahesh** [comment]
@mdshamoon I changed the **ttl** value and tried in different tabs. It is working fine

**Review by mdshamoon — APPROVED** [review]
I have also tested at my end and the changes looks good to merge.

**Pull request merged**
