### PR TITLE
menu improvements

### PR DESCRIPTION
**Pull request by kurund**

### CODE REVIEW

**Comment by mdshamoon** [comment]
Checked with Akhilesh and the main issue for him is still that we have to move out of one menu to hover over another as it hides the other icon. 

Let's update the menu position as well.

**Review by mdshamoon — COMMENTED** [review]
Checked with Akhilesh and the main issue for him is still that we have to move out of one menu to hover over another as it hides the other icon. 

Let's update the menu position as well.

**Comment by kurund** [comment]
@mdshamoon 

We will need to fix the cypress test after this is merged.

**Comment by kurund** [comment]
Just realised the mobile view needs some fixes. So let me fix that too.

**Comment by kurund** [comment]
@mdshamoon 

Ready for your review.

**Review by mdshamoon — APPROVED** [review]

**Pull request merged**
