### PR TITLE
Added support for deleting profile

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

Added support for deleting profile

### CODE REVIEW

**Comment by kurund** [comment]
@mdshamoon

As discussed can you please attach the flow for creating multiple profiles?

**Comment by mdshamoon** [comment]
@kurund this is the flow for creating and viewing profile https://cc.tides.coloredcow.com/flow/configure/2f35f885-5ed6-44d9-8877-8a25241b02f9. Please export it from here and import in your local

**Review by kurund — CHANGES_REQUESTED** [review]
@mdshamoon 

I don't see a delete button on the 
Screenshot 2023-02-23 at 23 48 17
profile screen.

Am I missing something?

**Comment by mdshamoon** [comment]
> @mdshamoon
> 
> I don't see a delete button on the Screenshot 2023-02-23 at 23 48 17 profile screen.
> 
> Am I missing something?

@kurund we hide delete button for simulator as people were deleting them. For testing you can just remove the hide logic for simulator in the code or test with an actual contact and Gupshup.

**Comment by kurund** [comment]
Working as expected.

**Pull request merged**
