### PR TITLE
Added validation for attachment URL

### PR DESCRIPTION
**Pull request by DigneshGujarathi**

### CODE REVIEW

**Comment by mdshamoon** [comment]
Are we also planning to add a loader because sometimes there is a delay in getting the response back and the user does not know what to do in that case?

**Comment by mdshamoon** [comment]
After clicking on OK I get the error URL is required even if the URL is present.
image

**Comment by DigneshGujarathi** [comment]
> Are we also planning to add a loader because sometimes there is a delay in getting the response back and the user does not know what to do in that case?

Checking with the backend on this

**Comment by mdshamoon** [comment]
Looks good.

**Pull request merged**
