### PR TITLE
Chat groups

### PR DESCRIPTION
**Pull request by kurund**
## Summary

* Implement Contacts | Group tab interface

## Test Plan

* Included in the PR

## Open items

- [x] Click on Groups tab and then switch back to Contacts, it fails
- [x] Sending message to group needs to be fixed
- [x] Update group messages cache after sending a message to the group
- [x] Starting flow to group needs to be fixed
- [x] Test cases need to be fixed
- [x] Load more functionality needs to be fixed
- [x] Message selection not working for Groups tab
- [x] Testing chat. and making sure it is not broken due to these changes
- [ ]  Add tests for new functionality

### CODE REVIEW

**Comment by DigneshGujarathi** [comment]
@kurund @mdshamoon 

https://user-images.githubusercontent.com/26589967/105351167-33040400-5c12-11eb-8c39-622f9290be50.mp4


I assigned myself to the default group, then went to the Group tab. Only send a Hi message, go back to the contact tab. The contact is continually changing and goes to the loop.

**Comment by mdshamoon** [comment]
@DigneshGujarathi can you take the latest backend pull and try again. Backend is not sending receive message subscriptions anymore for the group message.

**Comment by mdshamoon** [comment]
@DigneshGujarathi got the error. Backend has stopped the sent message subscription for the group message but they are still sending the tag and message status subscription due to which the contacts are behaving in this way.

**Comment by DigneshGujarathi** [comment]
> @DigneshGujarathi got the error. Backend has stopped the sent message subscription for the group message but they are still sending the tag and message status subscription due to which the contacts are behaving in this way.

Okay, but it will only update the cache. Why it's changing the contact? Is it overwriting the whole cache?

**Comment by kurund** [comment]
@DigneshGujarathi when the message is sent to the group, it sends the message to the individual contact. In contacts tabs, we always show the latest one first. Hence, once we receive the subscription the list gets updated.

**Comment by DigneshGujarathi** [comment]
> @DigneshGujarathi when the message is sent to the group, it sends the message to the individual contact. In contacts tabs, we always show the latest one first. Hence, once we receive the subscription the list gets updated.

Yeah, conversion list update is fine. The issue is it's changing the opened/selected contact. I had discussed this with @mdshamoon as per him this is happing because of tag & receive subscriptions.

**Comment by DigneshGujarathi** [comment]
@kurund @mdshamoon Create a group, go back to the chat screen. Now, click the Groups tab, it doesn't display the newly created group.

**Comment by mdshamoon** [comment]
> @kurund @mdshamoon Create a group, go back to the chat screen. Now, click the Groups tab, it doesn't display the newly created group.

@DigneshGujarathi Fixed this issue. Can you review and test again?

**Review by DigneshGujarathi — COMMENTED** [review]
Looks good

**Pull request merged**
