### PR TITLE
Fixes for flow keywords

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

- Removed restriction for having spaces in between multiple comma-separated flow keywords.
- Allow support for all languages

### CODE REVIEW

**Review by pankaj-ag — COMMENTED** [review]
Looks good to me. Can you make sure you trim the keywords before sending them to the backend?

**Comment by mdshamoon** [comment]
> Looks good to me. Can you make sure you trim the keywords before sending them to the backend?

Yes, They are trimmed from the frontend.

**Comment by pankaj-ag** [comment]
Can you please write the test case also?
Both Unit and cypress?

**Comment by mdshamoon** [comment]
> Can you please write the test case also?
> Both Unit and cypress?

Written unit test cases. @AkhileshNegi is working on the cypress test cases.

**Pull request merged**
