### PR TITLE
Package upgrade

### PR DESCRIPTION
**Pull request by kurund**
- [x] upgrade packages
- [x] fix any compatibility issue
- [x] unit test fixes
- [x] cypress test fixes

### CODE REVIEW

**Comment by mdshamoon** [comment]
@kurund downgrading "@apollo/client" to version "3.4.11" which is one version below the latest one since there are issues with jest coming up in these. Checking what could be the reason in the latest version.

**Comment by kurund** [comment]
@mdshamoon 

upgrading "@apollo/client" to version "3.4.13"  fixes earlier issues. Now we have only one failure.

```
src/App.test.tsx
```

**Comment by kurund** [comment]
@mdshamoon 

It would be good to fix the failing cypress test and merge this PR soon.

**Comment by kurund** [comment]
@mdshamoon ready for your review.

**Review by mdshamoon — APPROVED** [review]

**Pull request merged**
