### PR TITLE
Made header optional for interactive messages

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

Made header optional for interactive messages

## Test Plan

Added

### CODE REVIEW

**Comment by mdshamoon** [comment]
Waiting on the backend PR https://github.com/glific/glific/pull/1881 to merge. Cypress test cases are failing because of the backend dependency.

**Review by kurund — CHANGES_REQUESTED** [review]
@mdshamoon 
* title optional is working fine
* typing @ does not show any options see below screenshot.
Screenshot 2021-11-30 at 10 02 51 PM
* https://github.com/glific/glific-frontend/issues/1725 is not fixed. We are still allowing markdown in title. In my opinion we can allow * etc. Let's discuss this on call.

**Comment by mdshamoon** [comment]
@kurund somehow typing @ works for me 😅. Please can you recheck once or let me know the exact steps to replicate.
For #1725 we discussed in our standup and decided to just show the text as it is in the simulator instead of applying a check for markdown. We can discuss this in our standup.

**Comment by kurund** [comment]
@mdshamoon 

As discussed token list not working in edit mode, let's file a separate issue as it's also broken in master.

**Review by kurund — APPROVED** [review]
merging this PR.

**Pull request merged**
