### PR TITLE
Added multiple profiles selection in contact profiles area

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

Added multiple profiles selection in contact profiles area.

To test.

1. Enable contactProfiles by adding `is_contact_profile_enabled` to true
image

2. Restart backend server and login again.

3. Import flow profile registration [Profile Registration Workflow.json.zip](https://github.com/glific/glific-frontend/files/9451706/Profile.Registration.Workflow.json.zip)

4. Run this flow for simulator and create multiple profiles.

5. Visit contact-profile for simulator by going to the url: glific.test:3000/contact-profile/:id

### CODE REVIEW

**Review by kurund — CHANGES_REQUESTED** [review]
@mdshamoon 

I am receiving below error on https://glific.test:3000/user-profile
Screenshot 2022-09-09 at 15 06 11

**Review by kurund — CHANGES_REQUESTED** [review]
@mdshamoon 

Now I get a different error on https://glific.test:3000/user-profile

Screenshot 2022-09-10 at 23 18 01


Please note that https://glific.test:3000/contact-profile/1 is working fine.

**Comment by mdshamoon** [comment]
@kurund I have fixed the errors. Please have a look now

**Review by kurund — APPROVED** [review]
Looks good to me and working as expected.

**Pull request merged**
