### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by kurund**
## Summary

Updated React to the latest version along with a lot of related libraries.

### CODE REVIEW

**Comment by mdshamoon** [comment]
@kurund I checked the apollo client issue and it seems they have fixed the implementation for onCompleted callback. I tested on all areas where I changed in the previous PR and they all are working fine.

**Comment by mdshamoon** [comment]
Errors to fix:

1. Switching from chat to collection screen or vice-versa results in a blank screen
2. Messages getting repeated when sending continuously from chat screen
image

**Comment by mdshamoon** [comment]
Issues faces while testing in cypress:

- Not able to create a new search.
- Not able to move to collection screen as a staff member.

**Comment by kurund** [comment]
@mdshamoon 

On master, if you log in as a user with a `Staff` role you get below error in the console.

```
[GraphQL error]: Message: Unauthorized, Location: [object Object], Path: organization
```
It's failing due to:

```
query: "query provider {\n  organization {\n    organization {\n      bsp {\n        shortcode\n        __typename\n    
```

It loads the collection page.  This might be related.

**Comment by mdshamoon** [comment]
@kurund for roles and permission add roles_and_permssion row item to fun_with_flag table, after that restart the backend server and login again.

image

**Comment by mdshamoon** [comment]
@kurund this is the issue in our case https://github.com/apollographql/apollo-client/issues/9989

**Comment by mdshamoon** [comment]
@kurund fix the issue with emoji input. 

Seeing one more issue when we load images with react-image. The support for react 18 is not yet out for the library react-image https://github.com/mbrevda/react-image/issues/952

Will try alternative solutions for now.

**Pull request merged**
