### PR TITLE
Changed headers position to fixed

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

Changed headers position to fixed

### CODE REVIEW

**Review by kurund — CHANGES_REQUESTED** [review]
@mdshamoon 

The pager footer is sticky and working as expected. There is a test failure and looks related. Please check.

**Comment by kurund** [comment]
I have triggered a rerun for tests.

**Comment by mdshamoon** [comment]
@kurund fixed the test case in cypress

**Review by kurund — APPROVED** [review]
Looks good

**Pull request merged**
