### PR TITLE
Last message fixes

### PR DESCRIPTION
**Pull request by kurund**

### CODE REVIEW

**Review by mdshamoon — CHANGES_REQUESTED** [review]
There are some issues for messages with multiple lines

image

**Comment by kurund** [comment]
@mdshamoon 

The above display should be fixed now. I have also updated the result to show the search keyword part of the text.

**Review by mdshamoon — CHANGES_REQUESTED** [review]
It's taking some part of the second line for me. Can we make it only have the first line 
image

**Comment by kurund** [comment]
@mdshamoon 
Fixed.

**Review by mdshamoon — APPROVED** [review]

**Pull request merged**
