### PR TITLE
Possible fix for websocket reconnect bug

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

Added warning when socket connection breaks

### CODE REVIEW

**Review by kurund — CHANGES_REQUESTED** [review]
I am seeing a weird issue after these changes. Notification alert is now displayed on the Chat screen.

Screenshot 2022-02-23 at 11 47 41 PM

Here are the steps to replicate:
1. Edit a flow
2. Open preview
3. Then click on Chat
4. After few minutes you will see notification on the Chat screen.

**Comment by kurund** [comment]
I feel since we resetting WebSocket connection on clicking preview on Floweditor it's resulted in this conflict.

**Comment by mdshamoon** [comment]
> WebSocket

Resetting connection was causing some unwanted behaviours so removing that for now. Also the notification is system wide since the connection can break on any screen and user needs to be aware that the live messages will not come in that case.

**Review by kurund — APPROVED** [review]
Reload message is now shown correctly on Chat and Floweditor screens if the WebSocket connection is lost.

I made a minor correction. Good to merge once the test passes.

**Pull request merged**
