### PR TITLE
Added expression support for search

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

Added expression support for search

### CODE REVIEW

**Comment by mdshamoon** [comment]
@kurund fixing the cypress issues in the cypress repo as we have changed the way how we interact with calendar.

**Review by kurund — CHANGES_REQUESTED** [review]
@mdshamoon 

I don't see any option for using the expression in the UI.

Screenshot 2022-04-15 at 10 50 12 PM

**Comment by kurund** [comment]
@mdshamoon @abhi1203 

I wonder if we should use `Use relative dates` instead of `Use expression` label. Thoughts?

**Comment by mdshamoon** [comment]
> @mdshamoon
> 
> I don't see any option for using the expression in the UI.
> 
> Screenshot 2022-04-15 at 10 50 12 PM

@kurund for now we are only going with the expression in create search screen.

**Review by kurund — APPROVED** [review]
looks good.

**Pull request merged**
