### PR TITLE
Onboading page changes for issue #2102

### PR DESCRIPTION
**Pull request by enigmaticmahesh**
## Summary

Fix for Issue #2102

### CODE REVIEW

**Review by mdshamoon — CHANGES_REQUESTED** [review]
When I unselect the checkbox it gets hidden.
image

**Comment by enigmaticmahesh** [comment]
> When I unselect the checkbox it gets hidden. image

Fixed in this [commit](https://github.com/glific/glific-frontend/pull/2112/commits/e9acc4fc1f11f8698a7265ee79729056cc984a00) @mdshamoon

**Review by mdshamoon — CHANGES_REQUESTED** [review]
@enigmaticmahesh please check the tick color in the designs. It is white. Also please check the font weight and size of the label text. It seems different than the design
image

**Comment by enigmaticmahesh** [comment]
> @enigmaticmahesh please check the tick color in the designs. It is white. Also please check the font weight and size of the label text. It seems different than the design image

I have fixed the size and weight of the font but color of the tick we need to discuss @mdshamoon

**Review by mdshamoon — APPROVED** [review]

**Pull request merged**
